id: permit_edit_app
learningObjectives:
  - Craeting changes to role
hints:
  - Make sure you saved your changes
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "I need you to tick update and read actions and click save."
            delay: 3000
          - text: "When you do that, Permit generates the policy in real time and applies them to the enforcement points in the app!"
            delay: 3000
          - text: "Let me know when you have done it!"
            delay: 3000
trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: permit_api
            name: get_admin_role
            params:
              method: "get"
              url: "schema/${projectId}/dev/roles/admin"
        if:
          conditions:
            - conditionId: is_truthy
              params:
                value: ${outputs.get_admin_role.data?.permissions.length === 2}

          then:
            do:
              - actionId: bot_message
                params:
                  person: keen
                  messages:
                    - text: "Fantastic! I see the admin role has now only 2 permissions!"
                      delay: 3000
              - actionId: finish_step

          else:
            do:
              - actionId: bot_message
                params:
                  person: keen
                  messages:
                    - text: "Hmmmm... I see the admin role has only 2 permissions, can you try again?"
                  delay: 0
      else:
        do:
          - actionId: bot_message
            params:
              person: keen
              messages:
                - text: "OK. Let me know when you complete it."
                  delay: 2500
